name: Require “Allow Edits”

on: [pull_request_target]

permissions:
  contents: read

jobs:
  _:
    permissions:
      pull-requests: read  # for ljharb/require-allow-edits to check 'allow edits' on PR

    name: "Require “Allow Edits”"

    runs-on: ubuntu-latest

    steps:
      - uses: ljharb/require-allow-edits@2bf6dc5607979ae0e3f8739b9f9a4018e024b9a0 # @main
